name: Applications - Heat Map of SSL Versions
visualization:
  options:
    labelAngle: 37
    colorPalette: greenRed
    lx: Application Name
    includeHistogram: false
    ly: Application Version
    reversePalette: false
  type: heat-map
$schema: https://schemas.humio.com/query/v0.1.0
timeInterval:
  isLive: false
  start: 7d
queryString: |-
  // Find anything using an application with OpenSSL.
  #event_simpleName=InstalledApplication openssl

  // Group by the name and version, weight by distinct aids.
  | groupBy([AppName, AppVersion], function=count(aid, distinct=true, as=Endpoints), limit=max)

  // This can be lowered to find everything. We're just looking at 3 hits and above.
  | Endpoints>5
